### ISSUE TITLE
Null reference in GetCommentIdForProperty()

### ISSUE THREAD

**Issue by hstk** [domaindrivendev/Ahoy#100]
First, wanted to say that this is a great tool, thanks for putting it out there.

Running 6.0.0-beta9 on RC2, I'm finding some null reference exceptions in GetCommentIdForProperty(). jsonProperty.PropertyInfo() appears to never to get set. Changing null check seems to get things running again.
https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Annotations/XmlCommentsModelFilter.cs

        public void Apply(Schema model, ModelFilterContext context)
        {
            var commentId = XmlCommentsIdHelper.GetCommentIdForType(context.SystemType);
            var typeNode = _xmlNavigator.SelectSingleNode(string.Format(MemberXPath, commentId));

            if (typeNode != null)
            {
                var summaryNode = typeNode.SelectSingleNode(SummaryTag);
                if (summaryNode != null)
                    model.Description = summaryNode.ExtractContent();
            }

            foreach (var entry in model.Properties)
            {
                var jsonProperty = context.JsonObjectContract.Properties[entry.Key];
                //if (jsonProperty == null) continue;
                if (jsonProperty.PropertyInfo() == null) continue;

                ApplyPropertyComments(entry.Value, jsonProperty.PropertyInfo());
            }
        }

![applypropertycomments](https://cloud.githubusercontent.com/assets/12897758/16018402/5d1dec26-3172-11e6-8521-128eac1bd796.jpg)

**Comment by jeremyiverson** [comment]
I also have this issue. For now I am working around it by manually adding the OperationFilter and skipping the ModelFilter, which is what triggers the null error. The [IncludeXmlComments() method](https://github.com/domaindrivendev/Ahoy/blob/b178285ef09cbcd25a847a09f8d7bb7c99fe53c4/src/Swashbuckle.SwaggerGen/Application/SwaggerGenOptions.cs#L134-L139) includes both of these.

I updated my AddSwaggerGen as follows.

            services.AddSwaggerGen(options =>
            {
                // TODO The IncludeXmlComments() method adds both an OperationFilter
                // and a ModelFilter. The ModelFilter is hitting a NulReference exception.
                // For now, only add the operation filter.
                //options.IncludeXmlComments(pathToDoc);
                var xmlDoc = new XPathDocument(pathToDoc);
                options.OperationFilter<XmlCommentsOperationFilter>(xmlDoc);
            });

**Comment by gewoonrik** [comment]
I have copied the implementation of XmlCommentsModelFilter to my own project and have fixed it using https://github.com/domaindrivendev/Ahoy/pull/107/files. Then I used something like this:
```
services.AddSwaggerGen(options =>
        {
            var xmlDoc = new XPathDocument(pathToDoc);
            options.OperationFilter<XmlCommentsOperationFilter>(xmlDoc);
            options.ModelFilter<XmlCommentsModelFilter>(xmlDoc);
        });
```
