### ISSUE TITLE
Responses SwaggerResponse content-type header missing when returning content

### ISSUE THREAD

**Issue by JefStat** [domaindrivendev/Ahoy#108]
Little background I'm trying to get apiary's Dredd tests to run off of the swagger doc created by swashbuckle. http://dredd.readthedocs.io/en/latest/how-it-works/

SwaggerResponseAttribute does not have a field to include the response header into the swagger schema.
http://swagger.io/specification/#responseHeaders

**Comment by domaindrivendev** [comment]
Firstly, it's worth noting that SwaggerResponse has been reomved in favor of AspNet Core's built-in __ProducesResponseType__ attribute. However, this also doesn't allow you to specify response headers.

I would suggest you create your own custom attribute for this (e.g. ResponseHeadersAttribute) and then a corresponding IOperationFilter (see readme) that inspects each ApiDescription for the presence of that attribute. If it's there, then your filter can update the operation.responses accordingly. For an example of an IOperationFilter that inspects attributes on a controller/action and updates the operation accordingly you can check out the one in the SecuritySchemes example site:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/SecuritySchemes/Swagger/AssignSecurityRequirements.cs
