### ISSUE TITLE
Having trouble getting started with RC2

### ISSUE THREAD

**Issue by EltonInAtlanta** [domaindrivendev/Ahoy#110]
Hello, I'm developing with RC2 and .net 461.  Swagger gives me a 500 result, shown below.
Thanks for any advice.

Here is relevant chunks of project.json:

```
"dependencies": {
...
"Swashbuckle": "6.0.0-beta9",
...
}
"frameworks": {
    "net461": {
...
}}

"buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": false
  },
```
I've also tried "xmlDoc": true - same result.

My startup.cs:

```
 public void ConfigureServices(IServiceCollection services)
        {
           ...
            services.AddSwaggerGen();

also tried:
services.AddSwaggerGen(options =>
            {
                options.SingleApiVersion(new Info { Version = "v1", Title = "My Title" });
                options.DescribeAllEnumsAsStrings();
            });
...

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
...
app.UseSwaggerGen();
app.UseSwaggerUi();
            
```

My controllers look like this:
namespace wallet.Controllers
```
    [Route("api/[controller]")]
    public class WalletController : ControllerBase
...
[HttpGet]
        public async Task<IActionResult> Get()

```

Results:
![image](https://cloud.githubusercontent.com/assets/18667923/16384617/9c2a6c1a-3c57-11e6-9dc2-d5a7adad5240.png)

**Comment by rynowak** [comment]
If you're getting a 500, then chances are it's an unhandled exception.

Try adding the developer exception page `app.UseDeveloperExceptionPage()` https://github.com/aspnet/Diagnostics/blob/dev/samples/DeveloperExceptionPageSample/Startup.cs#L11

Then browse to the swagger endpoint `http://.../swagger/v1/swagger.json`

**Comment by EltonInAtlanta** [comment]
NotSupportedException: Unbounded HTTP verbs for path 'api/User'. Are you missing an HttpMethodAttribute?

**Comment by EltonInAtlanta** [comment]
Ok, so that meant exactly what it said.  I was missing [HttpGet] on a controller.

**Comment by EltonInAtlanta** [comment]
welllllll, it was working great - on local host.  on a test IIS, I get
Can't read swagger JSON from http://artemis/swagger/v1/swagger.json

The URL is http://artemis/wallet/swagger/ui/index.html
/wallet/ is the application under the default site on IIS.

**Comment by CristopherJonas** [comment]
@rynowak solution works for me...  Thanks man
