### ISSUE TITLE
Adding SwaggerConfig.cs support to Duplicate schemaIds

### ISSUE THREAD

**Issue by f7q** [domaindrivendev/Ahoy#119]
I Created Web API Servie.

But so, I got the message. `Conflicting schemaIds: Duplicate schemaIds detected for types {0} and {1}. `

Is Implementation this work to the Swagger6.0.0 in the roadmap?

Link 1. "[Error "Duplicate schemaIds detected" without schema name.](https://github.com/domaindrivendev/Swashbuckle/issues/738)"
Link 2. [SchemaRegistry.cs L122-L126](https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Generator/SchemaRegistry.cs#L122-L126)

**Comment by domaindrivendev** [comment]
I'm closing this because there's already support to provide a custom schema Id "strategy" when you encounter this issue. See __CustomSchemaIds__ on the AddSwagger setup action.
