### ISSUE TITLE
Unable to locate System.Xml.XPath >= 4.0.0-beta-23110

### ISSUE THREAD

**Issue by mattridgway** [domaindrivendev/Ahoy#12]
First time I've used Swashbuckle, added it into an empty vnext website created from webapi template in Visual Studio 2015 (RTM), got an error whilst restoring the packages in the package manager output "Unable to locate System.Xml.XPath >= 4.0.0-beta-23110".

I found that the most recently published version on the official nuget feed is "4.0.0-beta-23019" (https://www.nuget.org/packages/System.Xml.XPath/4.0.0-beta-23019).

The quick fix is to enable the vnext nightly nuget feed "https://www.myget.org/F/aspnetvnext" in your package sources. 

Considering beta5 packages have now been released, is it worth while removing the requirement on the nightly feed?

**Comment by domaindrivendev** [comment]
Good catch - I didn't realize the package was tied down to a specific version of System.Xml.XPath.

Actually I'm surprised that a specific version made it into the nuspec (generated by Visual Studio) given the following line in my project.json:

https://github.com/domaindrivendev/Ahoy/blob/6.0.0-beta2/src/Swashbuckle/project.json#L22

Anyway, modified it and published a new package with no requirement on the nightly feeds. I also took the opportunity to match the Swashbuckle beta number with that of AspNet.
