### ISSUE TITLE
SwaggerOperation fails to resolve Operation ID uniqueness issues

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Ahoy#125]
One of my controllers needs to provide 2 post methods. I used the SwaggerOperation attribute to differentiate the operation ids being generated for the two post methods, yet I am still seeing the error "NotSupportedException: Multiple operations with path 'api/Song' and method 'POST'. Are you overloading action methods?" This seems to be a bug, in that previous implementations would allow me to use 2 or more methods of the same verb as long as I changed the operation id using the attribute. If I remove one of the POST methods altogether, I can see that the operation id is indeed affected, but I can't have 2 POST methods due to the fact that the operation ID doesn't seem to be honored. 

Here's a sample from my controller code: 

        [HttpGet]
        [SwaggerOperation("GetAllSongs")]
        public IEnumerable<Song> Get()
        {
            return null;
        }

        [HttpPost]
        [SwaggerOperation("CreateSong")]
        public void Post([FromBody]Song song)
        {
        }

        [HttpPost]
        [SwaggerOperation("AddInstrumentToSong")]
        public void AddInstrument([FromBody] Instrument instrument)
        {
        }

**Comment by rynowak** [comment]
@bradygaster - what do you expect this to do at runtime? Based on the information you provided this will be ambiguous.

**Comment by bradygaster** [comment]
In the previous implementation (prior to Core), I could differentiate the various POST methods by operation id, using the SwaggerOperation annotation. Now, I can no longer do this. Is there an alternative?

**Comment by bradygaster** [comment]
Thanks to @rynowak I see the error in the assumptions I was making, that conventional routing would take over and do what I'd expected. Since conventional routing isn't how Web API will be routed, I needed to add specific routes to my API methods and things work as expected. 

This code fixes the issue: 

        [HttpGet]
        [SwaggerOperation("getAllSongs")]
        public IEnumerable<Song> Get()
        {
            return null;
        }

        [HttpPost]
        [SwaggerOperation("createSong")]
        [Route("song/createSong")]
        public void Post([FromBody]Song song)
        {
        }

        [HttpPost] 
        [SwaggerOperation("addInstrument")]
        [Route("song/addInstrument")]
        public void AddInstrument([FromBody] Instrument instrument)
        {
        }
