### ISSUE TITLE
Error generating when there is IFormFile as a parameter

### ISSUE THREAD

**Issue by mburumaxwell** [domaindrivendev/Ahoy#13]
Above I get an error by having an IList<IFormFile> in the parameters. This is for allowing file uploads. The stack trace doesn't make sense to me. Anyone have any idea. I haven't stepped into Ahoy's code yet to determine where exactly the error is

![ahoy stacktrace](https://cloud.githubusercontent.com/assets/1645026/8889519/13ab5bfe-32e6-11e5-8a28-bb865f500b1a.png)

**Comment by RehanSaeed** [comment]
I'm also trying to use IFormFile. I just get a text box for this property in the swagger page. Is it possible to change this to a file upload button?
