### ISSUE TITLE
SchemaRegistry in an IDocumentFilter implementation is null

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Ahoy#132]
Per [this previous issue](https://github.com/domaindrivendev/Ahoy/issues/120#issuecomment-232270409) @domaindrivendev calls out that SchemaRegistry should not be null in an IDocumentFilter implementation. In [this code fragment](https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Generator/SwaggerGenerator.cs#L56) it appears to be getting set as null. As a result IDocumentFilter implementors are somewhat crippled from extending the Swagger document.

**Comment by domaindrivendev** [comment]
null issue is fixed in beta902
