### ISSUE TITLE
Make an option to ignore controllers which are decorated with Obsolete attribute.

### ISSUE THREAD

**Issue by Deilan** [domaindrivendev/Ahoy#134]
IgnoreObsoleteActions and IgnoreObsoleteProperties are good. As a feature request it is proposed to make an option to make an option to ignore whole controllers (with all actions it in) which are decorated with Obsolete attribute.

**Comment by domaindrivendev** [comment]
If you want to ignore an entire controller, simply decorate it with the following:

```csharp
[ApiExplorerSettings(IgnoreApi = true)]
```
