### ISSUE TITLE
Write Swagger Document To File

### ISSUE THREAD

**Issue by danielmihai** [domaindrivendev/Ahoy#136]
Hello    @domaindrivendev ,

How can I write the SwaggerDocument when I start the application? 
I would like to use it for testing. 

How can I get it from the services.AddSwaggerGen or app.useSwagger ?

Thank you,
Daniel.

**Comment by anfomin** [comment]
@danielmihai you can download it via `TestServer`:

```C#
using (var server = new TestServer(new WebHostBuilder()
	.UseStartup<TStartup>()))
{
	var client = server.CreateClient();
	return await client.GetStringAsync($"path_to_the_swagger.json");
}
```

**Comment by domaindrivendev** [comment]
Closing as this is really a dup of #62. In summary, it's definitely something I want to implement but might a milestone or two down the road
