### ISSUE TITLE
Class description not showing anywhere in Swagger UI

### ISSUE THREAD

**Issue by kirk-marple** [domaindrivendev/Ahoy#137]
I have a class description in my Swagger JSON, but I'm not seeing that description anywhere in the generated GUI.  Class properties are coming through OK.

Class1 {
id (integer, optional): Identifier property. ,
property (string, optional): Property of string type.
}

Any options for enabling this, just to provide some more description on the data model class?

```
"definitions" : {
    "Class1" : {
        "description" : "Data model for stuff.",
        "type" : "object",
        "properties" : {
            "id" : {
                "format" : "int32",
                "description" : "Identifier property.",
                "type" : "integer"
            },
            "property" : {
                "description" : "Property of string type.",
                "type" : "string"
            }
        }
    }
},
```

**Comment by domaindrivendev** [comment]
Given that the generated Swagger is as expected, this is really an issue for the [swagger-ui](https://github.com/swagger-api/swagger-ui) folks.
