### ISSUE TITLE
Publish Swashbuckle.SwaggerGen separately?

### ISSUE THREAD

**Issue by dennisroche** [domaindrivendev/Ahoy#138]
Use case: replace the UI with alternative Swagger-compliant, however wanting to keep the `swagger.json` generator.

The existing `Swashbuckle` package can remain as is for those that want both. I'm happy to assist with packaging and adding CI etc. 

An alternative UI I would like to use is https://github.com/jensoleg/swagger-ui

**Comment by domaindrivendev** [comment]
This is already the case - the Swashbuckle package is merely a meta-package that bundles the others together. So, right now you can just pull in SwaggerGen independently of SwaggerUi

**Comment by dennisroche** [comment]
Ha, sorry. I don't know why I didn't see that. 

http://www.nuget.org/packages/Swashbuckle.SwaggerGen/
http://www.nuget.org/packages/Swashbuckle.SwaggerUi/

Great work by the way; Ahoy is nicer to configure than Swagger.
