### ISSUE TITLE
How to use Security Schemas?

### ISSUE THREAD

**Issue by xperiandri** [domaindrivendev/Ahoy#140]
Is there any explanation of how security schemas and authentication works with SwashBuckle?
I create an API using OpenIddict.
Now I have an AccountController and UI from default MVC Core template. So I use /Account/Login to manually login and use SwashBuckle with controllers that require authorization.
As I understand in case I remove that the only way will be to set up SwashBuckle to work with authentication.

Could someone write a guide of how to set it up? The sample is not too self descriptive.

**Comment by domaindrivendev** [comment]
Other than the example site, I haven't got round to documentation for this. However, there's lots of good resources out there to help you. First and foremost, I would recommend reading the [Swagger specification](http://swagger.io/specification) and in particular the sections on [Security Definitions](http://swagger.io/specification/#securityDefinitionsObject) and [Security Requirements](http://swagger.io/specification/#securityRequirementObject).

Once you've done this, you'll need to figure out how to describe your specific security scheme in Swagger, independently of Swashbuckle. Once you've done this, you can start configuring SB to output the appropriate Swagger. For this, I found the following resources which seem like they could be very useful:

http://knowyourtoolset.com/2015/08/secure-web-apis-with-swagger-swashbuckle-and-oauth2-part-1/
https://blogs.msdn.microsoft.com/pratushb/2016/04/28/enable-swagger-to-authenticate-against-azure-ad/
