### ISSUE TITLE
How to set UseFullTypeNameInSchemaIds in Ahoy?

### ISSUE THREAD

**Issue by NinoFloris** [domaindrivendev/Ahoy#145]
Ok so I've got my setup running but as the error points me to UseFullTypeNameInSchemaIds I have no clue how to set this. As it is nowhere to be found in SwaggerGenOptions

**Comment by domaindrivendev** [comment]
Oops ... that's not very helpful. Will add the method asap. In the meantime, you can use CustomSchemaIds and provide your own function for this

**Comment by NinoFloris** [comment]
Yes I found it, just returning type.FullName is enough indeed!

**Comment by JamieKeeling** [comment]
@domaindrivendev Will the UseFullTypeNameInSchemaIds be making an appearance in a future release?
