### ISSUE TITLE
Problem to generate swagger document when there is a constructor in controller

### ISSUE THREAD

**Issue by zh-wowtv** [domaindrivendev/Ahoy#147]
I got "Unable to Load SwaggerUI" error. My controller:

```
namespace TodoApi.Controllers
{
    [Route("api/[controller]")]  
    public class TodoController : Controller
    {
        public TodoController(ITodoRepository todoItems)
        {
            this.TodoItems = todoItems;
        }
```

It's working if I remove the constructor. How can I fix this issue? Thanks.

**Comment by zh-wowtv** [comment]
Sorry, I made a mistake. It's not because of the constructor. It's because I forgot the [httpget] attribute somewhere.

**Comment by LRPalacios** [comment]
This is actually usefull, i also was gettting this error, and it was because one of my controller actions was missing it's httpAction atributte
