### ISSUE TITLE
Swachbuckle Swagger support requried for .NET Core RTM release

### ISSUE THREAD

**Issue by freshdev1** [domaindrivendev/Ahoy#149]
Guys, I recently updated my .NET Core project to RTM version => 1.0.0. As per the guides, I had to remove the `imports` sections from my `project.json` in order to successfully migrate my project to 1.0.0 release. Prior to the update I had the following entries in my `project.json`:
```
"Swashbuckle": "6.0.0-beta9",
"Swashbuckle.SwaggerGen": "6.0.0-beta9",
"Swashbuckle.SwaggerUi": "6.0.0-beta9",
```
After the update the above lines start giving the following error:
```
Package Swashbuckle.SwaggerGen 6.0.0-beta9 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Swashbuckle.SwaggerGen 6.0.0-beta9 supports:
      - dnx451 (DNX,Version=v4.5.1)
      - dnxcore50 (DNXCore,Version=v5.0)
```
I then searched and found that RC1 is released for the Swagger as well. Then I updated the entries to the following:
```
"Swashbuckle": "6.0.0-rc1-final",
"Swashbuckle.SwaggerGen": "6.0.0-rc1-final",
"Swashbuckle.SwaggerUi": "6.0.0-rc1-final",
```
The same error is thrown even after upgrading the project to rc1. If I do add `imports` node to the `frameworks` section I start getting a lot of errors in services.AddMvc, services.Addoptions etc...

Please tell me if we have RTM support at the moment? Am I making any problem?

**Comment by RehanSaeed** [comment]
This is what you want:

```
  "dependencies": {
    "Swashbuckle": "6.0.0-beta901",
    "Swashbuckle.SwaggerGen": "6.0.0-beta901",
    "Swashbuckle.SwaggerUi": "6.0.0-beta901"
  },
```

**Comment by freshdev1** [comment]
Yes I did that after posting this issue and it was fixed. Well it was a very shocking thing for Me. Since I believe beta901 comes before RC1.

**Comment by domaindrivendev** [comment]
Yep I understand the confusion. I was trying to align with the Core milestones (rc1, rc2 etc.) but then decided "beta" was more reflective of this projects status so made the decision to switch back. All is fair in the pre-release world right :)

Also of note, you should only need to specify the "Swashbuckle" dependency as it already pulls in the other two

**Comment by freshdev1** [comment]
> All is fair in the pre-release world right :)

Pretty true! :) But this sometimes annoys, as well. :smile: But never mind keep up the good work guys! :+1: 

Thanks for the last note.

**Comment by CumpsD** [comment]
Ouch, just got burned on it too, used to just grabbing the top version of Nuget but then also got this error.

![image](https://cloud.githubusercontent.com/assets/1201644/19673701/71957ad8-9a82-11e6-94e9-c1be5b12afe1.png)

Isn't it an option to unlist that rc1 to avoid others running into it?
