### ISSUE TITLE
Info Version can only be set to v1 - should be able to be any string value.

### ISSUE THREAD

**Issue by devlynx** [domaindrivendev/Ahoy#153]
In the Startup method the Swagger Info object is initialized with a version appropriate for the API:

                ... c.SingleApiVersion(new Info
                {
                    Version = "1.2.3",
                    Title = "My API",
                    ...
                } ...

However, when the Swagger UI is set up, the SwaggerMiddleware is instantiated with a fixed URL of "/swagger/v1/swagger.json" (from SwaggerUiBuilderExtensions). Then in the SwaggerMiddleware the apiVersion is set to the "v1" from the fixed URL of "/swagger/v1/swagger.json" (in the RequestingSwaggerDocs method).

Finally in SwaggerGenerator the code:

            if (info == null)
                throw new UnknownApiVersion(apiVersion);

does not allow any Version other then what is in apiVersion which is fixed at "v1".

The Swagger Info Version property should allow any string value for display to the API consumer.

Thanks!

**Comment by domaindrivendev** [comment]
By design, the SwaggerGen and SwaggerUi components are strongly decoupled. As a result, if you change the version (or versions) provided through the former then you have to tell the UI component about the new URL for retrieving Swagger JSON from. For example:

    app.UseSwaggerUi(swaggerUrl: "/swagger/1.2.3/swagger.json)

**Comment by devlynx** [comment]
That's exactly what I need. Thanks for the quick response!
