### ISSUE TITLE
Type Error Swashbuckle.SwaggerGen.Annotations.XPathNavigatorExtensions.cs

### ISSUE THREAD

**Issue by Angelixion** [domaindrivendev/Ahoy#155]
Type error,  `public static class XPathNavigatorExtensiosn `should be `public static class XPathNavigatorExtensions`

**Comment by domaindrivendev** [comment]
Resolved by https://github.com/domaindrivendev/Ahoy/commit/b581953e7f0d081ffa40c93bcd2225a9b67c3336. File wasn't even being used!
