### ISSUE TITLE
CancellationToken is displayed as a model

### ISSUE THREAD

**Issue by gguillen** [domaindrivendev/Ahoy#161]
When a controller method contains a CancellationToken like so:

```c#
public async Task<IActionResult> GetItem(int id, CancellationToken cancellationToken)
```

it results in a model binding parameter field for each of the token properties on the Swagger UI.

The non Core swagger does not exhibit this behavior.

**Comment by JSkimming** [comment]
This has been reported in Swashbuckle with issue domaindrivendev/Swashbuckle#306. Based upon the examples in that issue we workaround it with this:

Create an operation filter that removes cancellation tokens.

```c#
public class CancellationTokenOperationFilter : IOperationFilter
{
    public void Apply(Operation operation, OperationFilterContext context)
    {
        ApiDescription apiDescription = context.ApiDescription;
        IEnumerable<IParameter> excludedParameters = apiDescription.ParameterDescriptions
            .Where(p =>
                p.ModelMetadata.ContainerType == typeof(CancellationToken) ||
                p.ModelMetadata.ContainerType == typeof(WaitHandle) ||
                p.ModelMetadata.ContainerType == typeof(SafeWaitHandle))
            .Select(p => operation.Parameters.FirstOrDefault(operationParam => operationParam.Name == p.Name));

        foreach (var parameter in excludedParameters)
            operation.Parameters.Remove(parameter);
    }
}
```

Then apply it globally in `Startup.ConfigureServices`.

```c#
services.AddSwaggerGen(options => options.OperationFilter<CancellationTokenOperationFilter>());
```

**Comment by gguillen** [comment]
I'm a bit confused then...  I always use CancellationToken and I have never seen this issue when using .net 4.6.1 with Owin and Swashbuckle.Core.  I stood up 2 projects in the last 2 weeks on that stack and do not have that issue.  How could this be?

**Comment by gguillen** [comment]
I think I figured it out.  It is not necessary to create a CancellationToken parameter in the controller method in ASP.NET Core.  The now exists HttpContext.RequestAborted that can be used in place of the parameter within a method.  When coded that way, the issue is resolved.
