### ISSUE TITLE
Using <remarks> to add Implementation Notes

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Ahoy#168]
My understanding is that the `<remarks>` section can contain Markdown like so:

```
<remarks>
# Heading 1
## Heading 2
### Heading 3
This is a paragraph
- This is a bullet point
<code>This is some code</code>
</remarks>
```

However, I can't get anything after the heading to render as it's meant to be:

![swagger](https://cloud.githubusercontent.com/assets/2270364/18242176/eb34ab00-734c-11e6-9d92-8087d5520442.png)

**Comment by SimonTouchtech** [comment]
What version of Swashbuckle are you using? This looks like the behavior that was fixed in beta902, or more specifically https://github.com/domaindrivendev/Ahoy/commit/0fddd538b793bfb39c0f155b2aeef69902f04cd4.

**Comment by RehanSaeed** [comment]
I had not spotted the new version.
