### ISSUE TITLE
Documenting Enum Integer and String Values

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Ahoy#170]
If my JSON contains several Enums, what is the best way to automatically generate documentation for them, such that the integer and string values for them are listed.

Is there an example of this somewhere I have not spotted?

**Comment by SimonTouchtech** [comment]
Not sure if this is what you're asking for, but the possible values for an enum can be seen in the generated JSON file available at <baseUrl>/swagger/v1/swagger.json by default. It can also be seen in swagger-ui by selecting "Model" in data type.

**Comment by RehanSaeed** [comment]
Had not spotted it in Model. That's similar to what I was wanting.
