### ISSUE TITLE
Swashbuckle appears to not be using my registered static files for the UI

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [domaindrivendev/Ahoy#174]
Hi there

My currently application is developed as modules.
Each of these modules gets loaded into the main application if the built version is located in a special modules folder.

I have a specific module that implements swashbuckle.

The module loads ok, and if I place a custom Index.html file and the corresponding css, in my Main application wwwroot folder, under swagger/ui, it gets loaded and used.

However, i'd like to load these files as static resources within my Module code.

I tried removing the files from wwwroot, and putting them inside my module, in a folder called /swagger/wwwroot.

I added the following to my Module code, and while it runs without error, it also does not use my custom index.html or css that reside within the swagger/wwwroot folder.
Is there a way to do this, without having to only place files directly in the wwwroot folder of the web application?   

public bool Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseStaticFiles("/swagger/wwwroot");

```
        // Enable middleware to serve generated Swagger as a JSON endpoint
        app.UseSwagger();

        // Enable middleware to serve swagger-ui assets (HTML, JS, CSS etc.)
        app.UseSwaggerUi();

        return true;
    }
```

**Comment by domaindrivendev** [comment]
So, if I'm understanding correctly, you're essentially trying to bundle your custom web assets (html, css) into a class library that can be referenced by an application to serve those assets?

I think this is more of a general AspNet Core question and isn't specific to Swashbuckle so I'm going to close the issue. However, it's exactly what I've done with the __Swashbuckle.SwaggerUi__ class library so I'm happy to describe the approach I've taken there as this might help.

Firstly, you'll need to tell the compiler to embed the assets into the DLL that's produced by your Swashbuckle module:

https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerUi/project.json#L6

Then, you wire up the built-in File Server middleware to serve those files from the embedded resources:

https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerUi/Application/SwaggerUiBuilderExtensions.cs#L25

It's also worth noting, if you're overriding some of the assets paths that come with SB by default (e.g. /swagger/index.html, /swagger/css/screen.css etc.) then you'll need to wire up your File Server middleware before the call to __UseSwaggerUi__.
