### ISSUE TITLE
SwaggerUi on Spartan IE

### ISSUE THREAD

**Issue by OzBob** [domaindrivendev/Ahoy#18]
On VS2015 (14.0.23107.0) download Zip of Ahoy, run project on Win10 VM on azure,  
Open in Project Spartan (IE vNext)
http://localhost:1417/swagger/ui/index.html
does not serve any pages but does on Chrome

**Comment by jderus** [comment]
I couldn't repro this problem using VS2015 RTM on Win10 non-VM.
Launched and worked in Chrome and Edge, using BasicApi as the startup project.

**Comment by OzBob** [comment]
I think because I had an pre-release version of win10VM from Azure, it has a crap version of Spartan.  I'll try on a newer version and if that's a problem raise another issue.  I have no idea how to get the version of Spartan installed on the VM, but I'll get a new version of win10 and try with Edge. I'm sure it's not a Ahoy issue.
