### ISSUE TITLE
Modelbinding parameters not binding

### ISSUE THREAD

**Issue by cable729** [domaindrivendev/Ahoy#182]
See below for screenshot and code to reproduce. Parameters of type `modelbinding` do not actually get populated with the value inputted when using the Swagger UI. However, if I make the request from Postman, the controller returns the expected result (and binds the method parameter correctly).

![image](https://cloud.githubusercontent.com/assets/1524578/18854408/780def3e-8408-11e6-8c59-8910e6a4fd56.png)

```
using Microsoft.AspNetCore.Mvc;

namespace WebApplication.Controllers
{
    public class Test
    {
        public string Name { get; set; }
        public bool IsPassing { get; set; }
    }

    [Route("api/[controller]")]
    public class TestController : Controller
    {
        [HttpPost]
        public Test CreateTest(Test test)
        {
            return test;
        }
    }
}
```

**Comment by Igmat** [comment]
Because "in" couldn't be a "modelbinding" in swagger specification. Just add `[FromBody]` attribute to your test parameter.

**Comment by cable729** [comment]
I'm not sure what you mean by "in". Can you elaborate?

P.S. the `[FromBody]` worked, but the input now has to be a JSON blob. This is a slightly different API then before.

**Comment by SimonTouchtech** [comment]
["in" is a property in the parameter object of Swagger JSON.](http://swagger.io/specification/#parameterObject) Values understood by Swagger UI are "query", "header", "path", "formData" and "body" (i.e. not "modelbinding").

The [default behavior of ASP.NET Core](https://docs.asp.net/en/latest/mvc/models/model-binding.html#how-model-binding-works) in model binding is (translated to Swagger language)
1. formData
2. path
3. query

I would suggest adding [FromForm] (formData), [FromRoute] (path) or [FromQuery] (query) depending on what you want to do. Perhaps you can even use all three if you want the default behavior but I don't know if it's possible and how Swashbuckle would handle it.

**Comment by Igmat** [comment]
@SimonTouchtech your last suggestion (using all of them) won't work because of Swagger schema, but everything else is quite right.

**Comment by cable729** [comment]
Hmm, I tried using `[FromForm]` like so:

```
    [Route("api/[controller]")]
    public class TestController : Controller
    {
        [HttpPost]
        public Test CreateTest([FromForm] Test test)
        {
            return test;
        }
    }
```

However, the model does not get bound from the swagger ui. Interestingly enough, the Curl command does not include the body:

```
curl -X POST --header 'Accept: application/json' 'http://localhost:17466/api/Test'
```

While the swagger ui does not pass in the form fields, if I try the same query from postman, the model is bound.

**Comment by cable729** [comment]
Here's the swagger ui response:

![image](https://cloud.githubusercontent.com/assets/1524578/18918354/c1888d7c-8557-11e6-8ca6-6819731f086d.png)

Here's the postman response:

![image](https://cloud.githubusercontent.com/assets/1524578/18918369/cc88e442-8557-11e6-9d4b-0e8572943407.png)

**Comment by SimonTouchtech** [comment]
That looks like a Swashbuckle bug to me, Parameter type should be "formData" and not "form" if I'm not mistaken.

**Comment by AlexKeySmith** [comment]
Is this related https://github.com/domaindrivendev/Ahoy/issues/81 ?

**Comment by domaindrivendev** [comment]
Yes this appears to be a dup of #81.
