### ISSUE TITLE
Schemes can't be set during configuration

### ISSUE THREAD

**Issue by NickDarvey** [domaindrivendev/Ahoy#187]
In version 5, a "schemes" array is added to the definition automatically,

> Schemes
> 
> If schemes are not explicitly provided in a Swagger 2.0 document, then the scheme used to access the docs is taken as the default. If your API supports multiple schemes and you want to be explicit about them, you can use the Schemes option.

but this doesn't happen in version 6. There is also no `options.Schemes()` during service configuration.

Azure API Management requires schemes to be in the Swagger definition, how can we can get our schemes to be listed?

**Comment by domaindrivendev** [comment]
Config coming in the next version. For now though you can set with a Document Filter (see readme)

**Comment by NickDarvey** [comment]
Thanks @domaindrivendev !

If anyone else is looking, stick this in your Startup.cs' `Configure()` method.
```
app.UseSwagger((doc, request) =>
{
    request.Schemes = new[] { "http", "https" };
});
```
