### ISSUE TITLE
Nothing happens when I try to use the Default field in a customized IDocumentFilter

### ISSUE THREAD

**Issue by furlanrapha** [domaindrivendev/Ahoy#188]
Hey guys,

I'm trying to generate a custom `IDocumentFilter` for one operation that I have. When I map a `path` parameter using `PartialSchema` it works fine, but when I try to use the `BodyParameter` with `Schema = new Schema { Type = "string", Default = "test" }` is not rendering when going to the Swagger UI.

Just wanted to know if this is a issue or to accomplish this I need to make in a different way.

Best regards,
Furlan.

**Comment by furlanrapha** [comment]
For better clarification:

``` csharp
new NonBodyParameter // THIS WORKS
{
   Default = "test",
   Name = "test1",
   Type = "string",
   In = "path"
},
new BodyParameter // THIS ONE DOESN'T WORK
{
    Schema = new Schema { Type = "string", Default = "test" },
    Name = "test2",
    In = "formData"
}
```

This code generates what you see in the image above:

![image](https://cloud.githubusercontent.com/assets/650119/19098118/00de6c2a-8a81-11e6-9659-5f6836e837f4.png)

**Comment by Igmat** [comment]
@furlanrapha `BodyParameter` have to be in "body", not in "formData".

**Comment by furlanrapha** [comment]
Thanks @Igmat!

You are correct, I used the wrong `In` type.
