### ISSUE TITLE
RC1 incompatible

### ISSUE THREAD

**Issue by elestedt** [domaindrivendev/Ahoy#189]
I'm using .NET Core 1..0.1 with .NET Framework 4.5.2 (because some dependencies have not been ported to .NET Core, namely the LDAP DirectoryServices in the framework itself).
When I try to use RC1 - it says that SwaggerGen and SwaggerUi are not compatible. .NET Framework 4.5.2 is a supported framework of .NET Core and hence it stands to reason that it would be supported by libraries as well?

**Comment by Igmat** [comment]
RC1 isn't latest version  of "Swashbuckle" package - use beta902 instead.

**Comment by elestedt** [comment]
That's just about as confusing as it can get... an RC that's older than a beta?

**Comment by Igmat** [comment]
This package has used same versions as ASP.NET Core, but after release of the last one, owner has decided go back to beta versions, because it doesn't ready for production yet.
