### ISSUE TITLE
Invalid swagger parameters generation

### ISSUE THREAD

**Issue by ravengerUA** [domaindrivendev/Ahoy#19]
if we have some param in the route, but we don't catch this parameter in action's parameters
````C#
    [Route("api/users/{userId}/[controller]")]
    public class OrdersController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Get(int orderId)
        {
            //// action code
        }
    }
````

we will get wrong swagger data for this parameter (without type)
````json
parameters: [
	{
		name: "orderId",
		in: "path",
		required: true,
		type: "integer",
		format: "int32"
	},
	{
		name: "userId",
		in: "path",
		required: true
	}
],
````

and swagger-ui 2.1.0 and greater couldn't render this file

**Comment by rynowak** [comment]
What's wrong about the data for `userId`? How do you expect us to infer the type?

This will show up in `ApiDescription` coming from MVC as untyped because we don't know what type to treat it as unless there's a declared parameter.

**Comment by domaindrivendev** [comment]
The parameter is missing the "type" which is a required Swagger property. Defaulting to "string" in this case seems appropriate.
