### ISSUE TITLE
SwaggerUiOptions removed from UseSwaggerUi middleware in .net core

### ISSUE THREAD

**Issue by skamal-IBP** [domaindrivendev/Ahoy#196]
Hi,

Why is the SwaggerUiOptions is removed form the UseSwaggerUi middleware.
Now the only parameter I see is "baseRoute" and "swaggerUrl".

I was trying to call "ConfigureOAuth2" method that is part of  SwaggerUiOptions  class.
Can we please have both as overload.?

Regards,
SYK.

**Comment by ehvattum** [comment]
Yes, I experience the same issue. It seems like the swaggerUi is not on the same version as the rest of swashbuckle/ahoy

**Comment by skamal-IBP** [comment]
I tried checking with the previous version, seems same parameter but no SwaggerUiOptions. Problems is documentation has the description about the SwaggerUiOptions implementation but the Nuget package Swashbuckle doesn't have. Just to mention its the only issue with .net core.

**Comment by gmsDave** [comment]
The published NuGet package hasn't been updated since Aug 14.  The UseSwaggerUi middleware that accepts the SwaggerUiOptions was only added on Sep 1.

**Comment by skamal-IBP** [comment]
Thanks..gmsDave... Now that makes sense..Will wait for the latest publish package then.
