### ISSUE TITLE
Include info.title in the the swagger.json output.

### ISSUE THREAD

**Issue by shaunluttin** [domaindrivendev/Ahoy#197]
The JSON Schema for Swagger UI 2.0 [requires info.title](https://github.com/OAI/OpenAPI-Specification/blob/39624ac7ee6960a5540e71a6b17a15f53b20048d/schemas/v2.0/schema.json#L87-L99):

```
"info": {
  "type": "object",
  "description": "General information about the API.",
  "required": [
    "version",
    "title"
  ],
  "additionalProperties": false,
  "patternProperties": {
    "^x-": {
      "$ref": "#/definitions/vendorExtension"
    }
},
```

The default swagger.json in Ahoy does not include `info.title`.

**Comment by shaunluttin** [comment]
We can set this manually like this: 

```
app.UseSwagger((r, d) => {
    d.Info.Title = "Foobar";
});
```

**Comment by domaindrivendev** [comment]
@shaunluttin - it's also worth noting that when the stable 6.0.0 release ships (days to go), the config. interface will have changed slightly and you'll be required to explicitly specify one or more SwaggerDoc's. For example:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Startup.cs#L39

This change is already available in the preview packages available on MyGet.
