### ISSUE TITLE
Setup should be done in the UseSwagger method

### ISSUE THREAD

**Issue by scabana** [domaindrivendev/Ahoy#20]
Hi, 

I'm starting to play with Swashbuckle for mvc6. At the moment, the options are set on the service instead of the application. This blocks a scenario where you would want to have multiple Swashbuckle setup like this: 

```csharp
 app.Map("/api/v1", v1App =>
                               {
                                   v1App.UseMvc();
                                   v1App.UseSwagger();
                               });
 app.Map("/api/v2", v2App =>
                               {
                                   v2App.UseMvc();
                                   v2App.UseSwagger();
                               });
```

Which would end up with two swagger endpoints, and that's what I want. I don't really care about discoverability of all api versions in my case.

My reason for doing this is that once I'm coding v2 api, I absolutely don't want the v1 api to change. If the swagger file is part of the v1 api and we configure the service instead of the application, this would mean that I have the v1 api swagger and v2 api swagger code in one single place. Adding api distinctions in that case would become increasingly difficult to maintain.

**Comment by scabana** [comment]
A little update, I was able to create a clean enough implementation using the ```MultipleApiVersions```. I made decentralized providers for each of my api version and use the ```versionSupportResolver``` agains't an array of those providers. Not as bad as initially thought.

**Comment by domaindrivendev** [comment]
Because you're configuring the ISwaggerProvider service and not the middleware, this (IMO) still makes the most sense where it is.
