### ISSUE TITLE
The example sites do not work outside the project directory.

### ISSUE THREAD

**Issue by aignas** [domaindrivendev/Ahoy#200]
Steps to reproduce:
1. Clone this git repository
2. Go to one of the examples: `cd test/Websites/CustomIndexHtml`
3. Try running it: `dotnet restore && dotnet run`
4. Notice that it complains that the Swashbuckle project does not have a lock file, which is unusual as it should work as a stand-alone project, but I suppose the fact that it is in the `test` folder makes it part of the project.
5. Go to the root of the project: `cd ../../..`
6. Restore NuGets for the whole project: `dotnet restore`
7. Go back: `cd -`
8. Check that now the example runs: `dotnet restore && dotnet run` now works
9. Copy the `test/Websites/CustomIndexHtml` outside the git repository and try `dotnet restore && dotnet run`. It will fail with the following error:

```
log  : Restoring packages for /Users/ia/src/experiments/dotnet/swagger/CustomIndexHtml/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /Users/ia/src/experiments/dotnet/swagger/CustomIndexHtml/project.lock.json
log  : /Users/ia/src/experiments/dotnet/swagger/CustomIndexHtml/project.json
log  : Restore completed in 6060ms.
Project CustomIndexHtml (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling CustomIndexHtml for .NETCoreApp,Version=v1.0
/usr/local/share/dotnet/dotnet compile-csc @/Users/ia/src/experiments/dotnet/swagger/CustomIndexHtml/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
/Users/ia/src/experiments/dotnet/swagger/CustomIndexHtml/Startup.cs(16,19): error CS1061: 'SwaggerGenOptions' does not contain a definition for 'SwaggerDoc' and no extension method 'SwaggerDoc' accepting a first argument of type 'SwaggerGenOptions' could be found (are you missing a using directive or an assembly reference?)
/Users/ia/src/experiments/dotnet/swagger/CustomIndexHtml/Startup.cs(27,30): error CS1660: Cannot convert lambda expression to type 'string' because it is not a delegate type

Compilation failed.
    0 Warning(s)
    2 Error(s)

Time elapsed 00:00:01.5763878
```

I assume that the NuGet published to nuget.org is different in some way and issues #196 and #186 and this issue are all related to the same cause.

**Comment by domaindrivendev** [comment]
This isn't an issue. The example projects are under the "test" folder because their purpose is to test the latest code in the "src" folder. They explicitly reference the "local" Swagger, SwaggerGen and SwaggerUi projects, as opposed to the corresponding Nuget packages, for this exact purpose.

So, if you only restore the example project without previously restoring the referenced Swashbuckle projects, you'll get an error. Or if you try run it standalone, it will try pull down and use the latest Nuget package but this is no good either because it was designed against the latest code, not the latest Nuget.

**Comment by isaacjrs** [comment]
Hi, so the UseSwaggerUi middleware doesn't accept the SwaggerUiOptions, are you planning to change that for the next release @domaindrivendev ?

**Comment by gmsDave** [comment]
@isaacjrs When the 6.0.0 milestone gets published to nuget, UseSwaggerUi will take a SwaggerUiOptions.  This is a new class added in late September.  The latest nuget package (6.0.0-beta902 as of this writing) was published on Aug 14.
