### ISSUE TITLE
Schema Example model doesn't honor DescribeAllEnumsAsStrings option

### ISSUE THREAD

**Issue by gmsDave** [domaindrivendev/Ahoy#203]
When defining an Example model using the ISchemaFilter method described in issue [162](https://github.com/domaindrivendev/Swashbuckle/issues/162) from the main repo for Swashbuckle (5-), enums are not displayed as strings but as their int values.

Given this model
![image](https://cloud.githubusercontent.com/assets/18301427/19615539/db24bc74-97bd-11e6-89ca-bf4a300b84ae.png)

and this controller
![image](https://cloud.githubusercontent.com/assets/18301427/19615548/fbe343ae-97bd-11e6-9801-393e70f46ada.png)

and this ISchemaFilter
![image](https://cloud.githubusercontent.com/assets/18301427/19615556/0bf036ee-97be-11e6-97d0-6a74e0b6128c.png)

The Model is displayed correctly in swagger
![image](https://cloud.githubusercontent.com/assets/18301427/19615590/a085f5d2-97be-11e6-8d61-e91344ca4651.png)

but the example shows int's, not strings
![image](https://cloud.githubusercontent.com/assets/18301427/19615593/b103d938-97be-11e6-812d-69423b4ba833.png)

I have uploaded a simple sample project recreating this [here](https://github.com/gmsDave/AhoyExample1).

**Comment by gmsDave** [comment]
I've done some debugging from the latest source trying to get to the bottom of this issue.  While I'm still new to this code base, I believe I've narrowed this down to the fact that the `JsonSerializer` created by the `SwaggerSerializerFactory` is returning a `JsonSerializer` without a `StringEnumConverter()` added to it.  If I manually add one immediately before [line 76](https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.Swagger/Application/SwaggerMiddleware.cs#L76) of SwaggerMiddleware.cs, I get a properly rendered Json enum:

![image](https://cloud.githubusercontent.com/assets/18301427/19747718/8b80954a-9b9a-11e6-95f4-4659651a4dd9.png)

for my strong-typed example

![image](https://cloud.githubusercontent.com/assets/18301427/19747729/a1737048-9b9a-11e6-8f26-dea7dcbf1b5a.png)

rather than this

![image](https://cloud.githubusercontent.com/assets/18301427/19747746/c3023870-9b9a-11e6-8311-bfb45bdd3aff.png)

Can anyone point me in the right direction on how the SwaggerSerializerFactory should be detecting that `DescribeAllEnumsAsString` was `true` and then adding the `StringEnumConverter()` converter to it?  Likewise, I suppose if `DescribeStringEnumsInCamelCase` is `true`, it should probably also set `CamelCaseText` to `true` on that converter?

**Comment by domaindrivendev** [comment]
I think this is a dup of #78

**Comment by gmsDave** [comment]
Agreed, it is the same underlying issue.

**Comment by veeravelu** [comment]
It is fixed now. use 
[JsonConverter(typeof(StringEnumConverter))]
public enum Action
{
    [EnumMember(Value = "value1")]
    Value1,
    [EnumMember(Value = "value2")]
    Value2,
    [EnumMember(Value = "value3")]
    Value3
};
