### ISSUE TITLE
XML documentation

### ISSUE THREAD

**Issue by rzachariah** [domaindrivendev/Ahoy#21]
Hi there,

This is more of a question than an issue, likely.

I'd like to include my XML documentation comments with my swagger documentation. What's the right way to do this with asp.net vnext?

I have a line like this:
c.IncludeXmlComments("<projectname>.xml");

But I get a FileNotFoundException, because I'm not actually producing any build outputs.

I'm trying to build my code into a Docker image and deploy it to Rancher. Everything works great, except I don't have the nice XML documentation comments I added to my Controller and Model.

Your project is awesome. Thank you!
Ranj

**Comment by mburumaxwell** [comment]
Hi,

In ASP.NET 5 you cannot set the output file name and location for your XML documentation, at least not yet. Thus I would not use that option but rather I would use an operation filter as shown in this pull request (https://github.com/domaindrivendev/Ahoy/pull/11).

However, you can still get XML docs if you produce outputs on build, This is explained [here  at SO](http://stackoverflow.com/questions/31126453/how-to-generate-xml-documentation-file-in-asp-net-5)
The task will be to find where the result XML document output is, and get the absolute path before passing it into the Swagger method/function.

**Comment by kirk-marple** [comment]
The problem I've found with this, in our ASP.NET 5 project, is there's an XML file generated per project/assembly.  When we deploy the API App to Azure, there's an XML for every package:

In this folder, there is {package-name}.xml:

/site/approot/packages/{package-name}/{version}/lib/dnx46

It looks like we'd need to collect up all the relevant XMLs from our packages into one file, and deploy to wwwroot, to make it easier for Swagger/Swashbuckle to find it.  The current working directory for that XML path below is /site/wwwroot.

                options.OperationFilter<ApplyXmlActionComments>(new ApplyXmlActionComments("{xml path}"));

Otherwise, we just can get the comments from the controllers in that main package, and none of the referenced classes in referenced packages.

**Comment by choudeshell** [comment]
You can use ```ILibraryManager``` to get the path of a given assembly and ultimately grab the XML documentation asset. If you have multiple assemblies that represent your APIs, then you'll need to manually combine them at the moment. 

```
            var localServiceProvider = services.BuildServiceProvider();
            var libraryManager = ActivatorUtilities.GetServiceOrCreateInstance<ILibraryManager>(localServiceProvider);
            var energyCapApi = libraryManager.GetLibrary("EnergyCap.Api");
            var energyCapApiDirectory = Directory.GetParent(energyCapApi.Path);
            var apiXmlDocs = energyCapApiDirectory.GetFiles("EnergyCap.Api.xml", SearchOption.AllDirectories).FirstOrDefault();

            services.AddSwagger(options =>
            {
                options.SwaggerGeneratorOptions.SingleApiVersion(new Info
                {
                    Version = "v3",
                    Title = "EnergyCAP v3 API",
                    Description = "",
                    TermsOfService = ""

                });
                options.SwaggerGeneratorOptions.SecurityDefinitions.Add("api_key", new ApiKeyScheme() { In = "header", Name = "api_key", Type = "apiKey" });
                options.SwaggerGeneratorOptions.Host = "";
                options.SwaggerGeneratorOptions.BasePath = "";
                options.SchemaGeneratorOptions.UseFullTypeNameInSchemaIds = true;

                if (apiXmlDocs != null)
                {
                    options.IncludeXmlComments(apiXmlDocs.FullName);
                }
            });
```

**Comment by kirk-marple** [comment]
@choudeshell Great, thanks, that's really useful information.

**Comment by rynowak** [comment]
@choudeshell - yep that's awesome!

**Comment by domaindrivendev** [comment]
@choudeshell - to clean things up a little further, you can create a constructor in your Startup class that takes an ILibraryManager. The framework will ensure it gets injected and so you won't have to build a local service provider

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Startup.cs for an example which uses IApplicationEnvironment to find the xml doc.

If you need to find Xml files within Nugets, you can inject ILibraryManager into your startup and follow the steps outlined above by @choudeshell

**Comment by RehanSaeed** [comment]
The following code can be used to get the documentation XML file path if you are using Azure:

```
options.OperationFilter(new ApplyXmlActionComments(GetXmlCommentPath()));

private string GetXmlCommentPath()
{
    var applicationName = this.applicationEnvironment.ApplicationName;
    var applicationVersion = this.applicationEnvironment.ApplicationVersion;
    var basePath = GetSolutionBasePath();
    var configuration = this.applicationEnvironment.Configuration;
    var runtimeIdentifier = this.applicationEnvironment.RuntimeFramework.Identifier;
    var runtimeVersion = this.applicationEnvironment.RuntimeFramework.Version.ToString().Replace(".", string.Empty);

    if (this.hostingEnvironment.IsDevelopment())
    {
        return $@"{basePath}\artifacts\bin\{applicationName}\{configuration}\{runtimeIdentifier}{runtimeVersion}\{applicationName}.xml";
    }

    // Azure file path
    return $@"{basePath}\packages\{applicationName}\{applicationVersion}\lib\{runtimeIdentifier}{runtimeVersion}\{applicationName}.xml";
}

private string GetSolutionBasePath()
{
    var directory = Directory.CreateDirectory(this.applicationEnvironment.ApplicationBasePath);

    while (directory.Parent != null)
    {
        if (directory.GetFiles("global.json").Any())
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new InvalidOperationException("Failed to detect solution base path - global.json not found.");
}
```

**Comment by MaurGi** [comment]
This does not work in Azure with Asp.Net Core RC 1. I get a 500 error and the app can't start - we should reopen this issue and fix it when Asp.Net is released.

**Comment by mburumaxwell** [comment]
I have mine working right now on Azure very well; I just checked. Are you using Swashbuckle `6.0.0-rc1-final`? Could you share a snippet or some sought of extra information on how you wired up Swashbuckle?

**Comment by bragma** [comment]
@RehanSaeed  Same problem here on azure web app... 500 error and app can't start.
My setup is:

```
			services.AddSwaggerGen();

			services.ConfigureSwaggerDocument(options =>
			{
				options.SingleApiVersion(new Swashbuckle.SwaggerGen.Info
				{
					Version = "v1",
					Title = "MyApi API"
				});

				options.OperationFilter(new ApplyXmlActionComments(GetXmlCommentPath()));
			});
			services.ConfigureSwaggerSchema(options =>
			{
				options.DescribeAllEnumsAsStrings = true;
			});
```

**Comment by bragma** [comment]
@MaurGi 
I've found the problem. As you see GetXmlCommentPath on Azure expects to find your application inside the packages folder. This is deployed only if you select an option in VS Publish.

Check "settings -> File publish options" and enable "Compile source files into NuGet packages".
