### ISSUE TITLE
Restrict access to the documentation

### ISSUE THREAD

**Issue by waldo2188** [domaindrivendev/Ahoy#215]
Sometime, we must restrict access to the documentation and only authenticated user can access.

So, is there a way so that only the authenticated user can access the /swagger/v1/swagger.json and the Swagger UI ?

Thanks.

**Comment by alexvaluyskiy** [comment]
Try Http Authentication

**Comment by waldo2188** [comment]
I Think in something more advanced. Like using a OpenId Connect User provider.
By this way I can easily manage users.

**Comment by ahofman** [comment]
You could achieve this in your HTTP pipeline configuration in Startup. 
Assuming you're already using some authentication middleware (like `app.UseOpenIdConnectAuthentication()`), try adding something like this, after your authentication middleware and before `app.UseSwagger()` and `app.UseSwaggerUi()` 

    app.Use(async (ctx, next) =>
            {
                if (ctx.User != null &&
                    ctx.User.Identity != null &&
                    ctx.User.Identity.IsAuthenticated)
                {
                    // If you're authenticated, proceed
                    await next();
                }
                else
                {
                    // If you're not authenticated, do not proceed
                    // and issue an authentication challenge
                    await ctx.Authentication.ChallengeAsync();
                }
            });

**Comment by domaindrivendev** [comment]
@ahofman is spot on. Swashbuckle doesn't support authorization to view docs out-of-the-box but it can easily be accomplished with the extensibility native to AspNet Core.

If someone does get a working example together, please consider submitting a PR to have it added to the test/Websites folder in this repo.

**Comment by waldo2188** [comment]
Sorry for the delay (stuck in an other universe)

So, I've try the code given by @ahofman, and it's work very well (Thanks !)

I paste here the code I use with somes light modifications to fit my needs : 

```C#
// I check if the request concerne only swagger
if (ctx.Request.HttpContext.Request.Path.ToString().Contains("/swagger/") &&
    ctx.User != null &&
    ctx.User.Identity != null &&
    ctx.User.Identity.IsAuthenticated)
   {   // Check if the user has the right right
       if (ctx.User.HasClaim(c => c.Type == "role" && c.Value == "doc.authapi"))
       {
           // If you're authenticated, proceed
           await next();
       }
       else
       {
           ctx.Response.StatusCode = (int)HttpStatusCode.Forbidden;
        }
  }
  else
 {
     // If you're not authenticated, do not proceed
     // and issue an authentication challenge
     await ctx.Authentication.ChallengeAsync();
  }
});
```
