### ISSUE TITLE
Configure UI with beta901/902. Inject custom javascript ?

### ISSUE THREAD

**Issue by l3lade** [domaindrivendev/Ahoy#221]
Can't we do the following with "Swashbuckle.SwaggerGen": "6.0.0-beta901" and   "Swashbuckle.SwaggerUi": "6.0.0-beta901" ? Is there a way to inject custom javascript with this version ?

We can't go for rc1 as we are targeting 4.6 and rc1-final doesn't yet support it.

app.UseSwaggerUi(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "V1 Docs");
                c.EnabledValidator();
                c.BooleanValues(new object[] { 0, 1 });
                c.DocExpansion("full");
                c.SupportedSubmitMethods(new[] { "get", "post", "put", "patch" });
                c.InjectOnCompleteJavaScript("/ext/custom-script.js");
                c.InjectStylesheet("/ext/custom-stylesheet.css");
            });

**Comment by alexvaluyskiy** [comment]
The package from the myget feed can do it

**Comment by domaindrivendev** [comment]
Will be available in the stable 6.0.0 release (days to go) and as @alexlukelevy mentioned, it's also currently available as a preview package on MyGet.

For some sample code, checkout the following:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/CustomUiConfig/Startup.cs#L27

**Comment by l3lade** [comment]
ty
