### ISSUE TITLE
Support OpenId Connect id_token?

### ISSUE THREAD

**Issue by ahofman** [domaindrivendev/Ahoy#224]
Presently the only responses we can get from an OAuth2 authorization endpoint is response_type=code  or response_type=token. 

We secure our API with OpenID Connect, and we therefore require response_type=id_token. 

Can I suggest adding a new field to `SwaggerUiOptions.ConfigureOAuth2` called "responseType" that indicates what the value of response_type should be. When blank, it can default to the current behaviour, i.e., "token" when flow is implicit, "code" otherwise. 

**Edit**: I've realised this is a swagger-ui issue, already alluded to [here](https://github.com/swagger-api/swagger-ui/issues/1974), and not related to swashbuckle - closing this issue.

**Comment by VictorioBerra** [comment]
https://github.com/swagger-api/swagger-ui/issues/1974

I think this is not just a swagger-ui issue.  `OAuthConfigObject` is missing stuff. Like scopes, response type. Everything that you would expect to be passed to `window.swaggerUiAuth`.
