### ISSUE TITLE
Swagger-ui.js get error 500

### ISSUE THREAD

**Issue by zhangxin511** [domaindrivendev/Ahoy#23]
I am working on a sample application, I have swagger running fine on windows using 1.0.0-beta7 coreclr x64, by running dnu web command. But using the same code running on Ubuntu 14.04 but run 'dnx kestrel', also same 1.0.0-beta7 coreclr x64, I am not able to have correct swagger ui rendered. To be specific: I got 500 for a static file:Swagger-ui.js

index.html	200	document	Other	4.6 KB	200 ms	
reset.css	304	stylesheet	index.html:9	201 B	89 ms	
screen.css	304	stylesheet	index.html:10	201 B	90 ms	
typography.css	304	stylesheet	index.html:8	201 B	89 ms	
jquery-1.8.0.min.js	304	script	index.html:13	215 B	85 ms	
jquery.slideto.min.js	304	script	index.html:14	215 B	85 ms	
jquery.wiggle.min.js	304	script	index.html:15	215 B	86 ms	
handlebars-2.0.0.js	304	script	index.html:17	215 B	89 ms	
underscore-min.js	304	script	index.html:18	215 B	98 ms	
swagger-ui.js	500	script	index.html:20	0 B	193 ms	
backbone-min.js	304	script	index.html:19	215 B	98 ms	
jquery.ba-bbq.min.js	304	script	index.html:16	215 B	96 ms	
marked.js	304	script	index.html:22	215 B	97 ms	
highlight.7.3.pack.js	304	script	index.html:21	215 B	96 ms	
swagger-oauth.js	304	script	index.html:23	215 B	97 ms	
print.css	304	stylesheet	index.html:12	201 B	15 ms	
logo_small.png	304	png	jquery-1.8.0.min.js:2	202 B	4 ms	
droid-sans-v6-latin-700.woff2	304	font	jquery-1.8.0.min.js:2	215 B	4 ms	
favicon-16x16.png	200	png	Other	858 B	11 ms	
favicon-32x32.png	304	png	Other	202 B	3 ms

**Comment by zhangxin511** [comment]
I can walk around this by switch to swagger-ui.min.js in index.html. But then it will render junk characters from index.html make things funny. After tweak the source code, it seems:
var template = _resourceAssembly.GetManifestResourceStream("Swashbuckle.SwaggerUi.index.html"); is not working properly with coreclr beta7 version. 

I changed to following line, and I know this is a hard fix,
string text = File.ReadAllText(@"../Swashbuckle/SwaggerUi/index.html");
At least it working now in linux using dnx kestrel.

**Comment by domaindrivendev** [comment]
@zhangxin511 - are you still experiencing this issue with beta8?

**Comment by zhangxin511** [comment]
@domaindrivendev  Thanks for the follow up. The error do goes away when I update to beta-8, I have removed my own customized code for walk-around, page still renders correctly and I don't find any issues yet both on windows and linux.
