### ISSUE TITLE
Swashbuckle doesn't work with ASP.NET 5.0 on beta8

### ISSUE THREAD

**Issue by serkanpektas** [domaindrivendev/Ahoy#25]

**Comment by domaindrivendev** [comment]
I'm not seeing beta8 released to the official nuget feed yet. According to this - https://github.com/aspnet/Home/wiki/Roadmap, it won't be released until October.

My goal for SB is to align it's beta releases with the "official" AspNet 5.0 beta releases. I don't want to release a package that has dependencies on the AspNet nightlies

**Comment by Jak3b0** [comment]
Any timeframe to support the newly released beta 8? :D

**Comment by adamrogas** [comment]
Is this update going to be supported on nuget
