### ISSUE TITLE
Beta7, XmlComments

### ISSUE THREAD

**Issue by sandorfr** [domaindrivendev/Ahoy#27]
Looks like you changed the way we apply xml comments. The handy `IncludeXmlComments` has been replaced by the less handy :
```csharp
options.ModelFilter(new Swashbuckle.Swagger.XmlComments.ApplyXmlTypeComments("pathtoxmlcomments"));
options.ModelFilter(new Swashbuckle.Swagger.XmlComments.ApplyXmlActionComments("pathtoxmlcomments"")));          
```
the issue is that you left an unintentional `new()` constraint on the ModelFilter overload which takes an instance as argument. So it won't compile.

BTW, it looks like there is no easy way to configure schemes anymore. I had to write a DocumentFilter. Not sure why remove such feature.

**Comment by domaindrivendev** [comment]
Well, the configuration API is in a bit of flux at the moment. I'm not overly happy with the new .Net IOptions model because it encourages mutable value objects but at the same time I want to be consistent with new patterns. I'm still playing with a few ideas.

Apologies for the breaking changes but it is in beta so I'm not going to make too make any guarantees. But, I'll definitely address both of your issues with the upcoming beta8 release.

Thanks for the feedback - it's really helpful

**Comment by sandorfr** [comment]
Ok, great. I kinda lkike the IOptions model but I understand you point.
I definitely get the beta / breaking changes things :) I break my own code every day and that's part of the fun. So, no need for an apology and thanks for the good work anyway.

**Comment by kirk-marple** [comment]
@domaindrivendev In the beta8 release, would you mind summarizing the right approach to incorporate XML comments into Swagger?  Did anything change from beta 7, or do we still need to manually add ApplyXmlTypeComments and ApplyXmlActionComments?

**Comment by sandorfr** [comment]
@kirk-marple nothing changed as far as I know of. To make it work I had to use this workaround :
```
 public class ApplyXmlTypeCommentsFixed : ApplyXmlTypeComments
    {
        public ApplyXmlTypeCommentsFixed() : base("")
        {
            throw new NotImplementedException();
        }

        public ApplyXmlTypeCommentsFixed(string filePath): base(filePath)
        {

        }
    }

    public class ApplyXmlActionCommentsFixed : ApplyXmlActionComments
    {
        public ApplyXmlActionCommentsFixed() : base("")
        {
            throw new NotImplementedException();
        }

        public ApplyXmlActionCommentsFixed(string filePath): base(filePath)
        {

        }
    }
```

And use those class as filters.

```
 services.ConfigureSwaggerSchema(options =>
            {
                options.ModelFilter(new ApplyXmlTypeCommentsFixed(Path.Combine(appEnv.ApplicationBasePath, "Swagger/VRtuoz.xml")));
            });

 services.ConfigureSwaggerDocument(options =>
            {
                             options.OperationFilter(new ApplyXmlActionCommentsFixed(Path.Combine(appEnv.ApplicationBasePath, "Swagger/VRtuoz.xml")));

```

Hope this helps.

**Comment by sandorfr** [comment]
Apparently a fix (https://github.com/domaindrivendev/Ahoy/pull/28) has been merge so the workaround is useless now.

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Startup.cs for a simplified approach for wiring up Xml comments
