### ISSUE TITLE
UI page not rendering

### ISSUE THREAD

**Issue by takazm** [domaindrivendev/Ahoy#29]
Not sure if I'm doing anything wrong. I have referenced and done the whole setup in the startup class as follows:

     public void ConfigureServices(IServiceCollection services)
        {
             services.AddMvc();
           services.AddSwagger();

      }

  public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseStaticFiles();
            app.UseMvc();
            app.UseIdentity();
            app.UseSwagger();
            app.UseSwaggerUi();
        }
when I launch and navigate to the doc url e.g. http://localhost:44023/swagger/ui/index.html
there is no doc end-point listed. It basically fails to render the ui. I checked the network calls and I can see the json results coming back from the server but no ui is rendered.

I do see that there is a javascript error after the response comes back in the swagger-ui.min.js: "Invalid string length"

![swaggerjs](https://cloud.githubusercontent.com/assets/5674007/10409935/3ac503ba-6f32-11e5-9079-c02884993fdd.PNG)
![swagger-json](https://cloud.githubusercontent.com/assets/5674007/10409934/3ac4f064-6f32-11e5-95d2-2c8189b114c2.PNG)
![swaggerui](https://cloud.githubusercontent.com/assets/5674007/10409933/3abc18f4-6f32-11e5-94af-9277f0f5ba91.PNG)

**Comment by domaindrivendev** [comment]
@takazm if you're still experiencing this issue could you take the generated Swagger and run it through the online validator - POST to http://online.swagger.io/validator/debug?

**Comment by takazm** [comment]
I updated to the latest version and it seems to have sorted the issue. Thanks
