### ISSUE TITLE
beta8: Swagger basePath validation error

### ISSUE THREAD

**Issue by kirk-marple** [domaindrivendev/Ahoy#36]
First, thanks for getting the beta8 build out.  I've gotten it integrated successfully, except for one glitch. 

The Swagger UI loads but my Swagger JSON won't validate properly.

I get this error:

[{"level":"error","domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^/\" does not match input string \"\"","schema":{"loadingURI":"#","pointer":"/properties/basePath"},"instance":{"pointer":"/basePath"}}]

My guess is that it's from having a null basePath?

I'd actually prefer to have a basePath of /api/v1, and have the rest of the paths be relative.

Is this configurable via Swashbuckle?

	"swagger": "2.0",
	"info": {
		"version": "v1",
		"title": "API V1"
	},
	"basePath": "",
	"paths": {
		"/api/v1/vendors/{vendorId}/applications": {

**Comment by arichika** [comment]
RC1 has the same problem.  
  
https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.Swagger/Application/SwaggerDocsMIddleware.cs#L46  
  
I found that  "httpContext.Request.PathBase" is null.  This Param is provided by the "Microsoft.AspNet.Http", Anyone (under the Microsoft.AspNet.Http) not set this parameter.
  
Sloppy Resolution, e.g.
```
// var swagger = _swaggerProvider.GetSwagger(apiVersion, null, httpContext.Request.PathBase);
var swagger = _swaggerProvider.GetSwagger(apiVersion, null, "/" + httpContext.Request.PathBase.Value); // sloppy, slack, 
```  
In Swashbuckle beta6,  We could set BasePath parameter. e.g.
```
public static void ConfigureServices(IServiceCollection s)
{
s.AddSwagger(
    config =>
    {
        config.SwaggerGeneratorOptions.BasePath = "/";
```
I don't found same functional way in RC1.
