### ISSUE TITLE
Wrong Namespace for AddSwagger() Extension on RC1

### ISSUE THREAD

**Issue by endeffects** [domaindrivendev/Ahoy#37]
Hallo,

your Namespace for the AddSwagger Extension is wrong for RC1. It was renamed by Microsoft a few weeks ago. Microsoft.Framework.* is now Microsoft.Extensions.*

namespace Microsoft.Framework.DependencyInjection 

HAS TO BE 

namespace Microsoft.Extensions.DependencyInjection
{
    public static class SwaggerServiceCollectionExtensions
    {
        public static void AddSwagger(this IServiceCollection services)
        {

**Comment by jwuliger** [comment]
@endeffects Were you able to work around this? I am having the same problem.

**Comment by endeffects** [comment]
No, i'm just waiting for the update. The only solution to fix this by your own is to fork the repository and upgrade the dependencies by your own.

**Comment by mcliment** [comment]
There's already a PR #40 with the library updated to rc1-final.

**Comment by jwuliger** [comment]
That is crazy! I pulled via zip and updated it also. The only thing I missed was the path strings. This is great. Saved my life. Thanks!

**Comment by endeffects** [comment]
well, the problem exists for rc2 too.

**Comment by jwuliger** [comment]
Hmmmm. Gotta love cutting edge development!

**Comment by oldnerd** [comment]
will there be a nuget package with the support for rc1-final?  If it's forthcoming soonish I can save the time needed to clone and build this into the api project.

**Comment by domaindrivendev** [comment]
Being a "release candidate", there's additional cleanup other than just ramping the aspnet version that I want in the next release.

Coming soon though (1-2 weeks) ...

**Comment by snissim** [comment]
+1 for the -rc1-final nuget package whenever it's ready. Swashbuckle is great, thanks to everyone who contributes!

**Comment by mellogrand** [comment]
+1 for the -rc1-final nuget package  badly needed. Should be easy to do at least with PR #40  fixed

**Comment by kirk-marple** [comment]
+1 here as well; really need this ASAP for our project.

**Comment by damienpontifex** [comment]
:+1: also interested in a -rc1-final release to nuget

**Comment by domaindrivendev** [comment]
Hey all, I released this late last night and then ran into local environment issues trying to test out via the nuget feed.

If you get a chance, please pull it down and let me know if it's working.

Cheers

**Comment by damienpontifex** [comment]
Testing basic swagger UI and json metadata and seems to be working fine for me. Thank you

**Comment by endeffects** [comment]
As aspected the same problem exists for rc2 :)
