### ISSUE TITLE
beta5 version: rebuild solution

### ISSUE THREAD

**Issue by lesikDev** [domaindrivendev/Ahoy#4]
Hello!

Can you, please, update Swashbuckle for beta5?
I use "Microsoft.AspNet.Mvc": "6.0.0-beta5-*" and my dnx version is dnx-clr-win-x86.1.0.0-beta5-11682. 

Thank you.

**Comment by operezfuentes** [comment]
Hi asp.net beta5 has renamed some Configuration pacakges.

services.AddSwagger is using old packages that has been renamed in beta5 version:

Microsoft.Framework.DependencyInjection.Interfaces

Configuration packages should be new referenced in solution.

Thanks!

**Comment by domaindrivendev** [comment]
Should all be resolved in latest release (targeted to beta5) - Swashbuckle 6.0.0-beta2
