### ISSUE TITLE
Example of setting service method response type?

### ISSUE THREAD

**Issue by oldnerd** [domaindrivendev/Ahoy#41]
This may be a silly question reflecting a service with odd code.

I have a simple service that returns an object using Aspnet 5 rc1.  Method declaration looks like:

public ActionResult GetByProductId(int productId) => new ObjectResult(_productInfoRepository.DescribeProductByProductId(productId));

Where the respository returns a Product object.

Understandably - swagger isn't reflecting that response type.  Is there an annotation I should be using to mark up the method to reflect the actual response type the client will be seeing?

Thanks

**Comment by oldnerd** [comment]
Sorry - had this right; debugger was holding an old version open.  User error.

**Comment by rynowak** [comment]
For anyone else that happens upon this issue, the attribute is `[Produces(typeof(Product))]`
