### ISSUE TITLE
Bare bones installation guide?

### ISSUE THREAD

**Issue by samuraiken** [domaindrivendev/Ahoy#44]
Hey guys!

So I found out about Swagger a few days ago - but as I am in *.rc1-final of the MVC tooling it looks like Ahoy is my only real option for Swagger integration (outside of doing it by hand, of course).

 I looked at the pull request with partial install instructions, but that is targeted as RC8, and I know there were some changes that mattered from there to rc1.

If we could get any sort of guidance, I will be happy to get it running and write a more significant bit of text on the process and contribute that back into the codebase. 

Thanks for all your work in any case.

**Comment by shederman** [comment]
+1

I've tried using the guide at https://www.myget.org/feed/swashbuckle/package/nuget/Swashbuckle.Swagger

I've tried using the Startup.cs and project.json in the Ahoy Test projects

I've tried using this feed: https://www.myget.org/gallery/swashbuckle

Nothing works. At all.

**Comment by shederman** [comment]
I eventually did a whole bunch of refactoring and built my own nupkg for it. A bit of a pain, but will tide me over for now.

**Comment by Schandlich** [comment]
@shederman Any chance you could share that nupkg? The lack of documentation is rather frustrating...

**Comment by domaindrivendev** [comment]
This is all in pre-release at the mo - just don't got the time to build the docs yet.

I would say check out the examples in the test/Websites folder. Look at the Startup files - it's pretty straightforward.

Feel free to submit a PR with the docs

**Comment by seburgi** [comment]
@shederman have you tried using the official nuget package? https://www.nuget.org/packages/Swashbuckle/6.0.0-rc1-final

**Comment by Schandlich** [comment]
@domaindrivendev @shederman Issue was between the chair and keyboard. Should have been more aware of how it was configured. Default url is <your-root-url>/swagger/ui. Not <your-root-url>/swagger as the documentation for Swagger shows. Thanks!

**Comment by shederman** [comment]
Sorry for lack of reply, was away on holiday. I found that the tests/Websites didn't even compile.

**Comment by domaindrivendev** [comment]
They compile and work for me. Which version of dnx do you have installed?

**Comment by shederman** [comment]
rc1. Will try again and check.

**Comment by shederman** [comment]
Tried again, deleted the repository, fetches everything again, and it built fine. Going to go with "gremlins" :-)
