### ISSUE TITLE
RC1 publish

### ISSUE THREAD

**Issue by adamhathcock** [domaindrivendev/Ahoy#45]
Any chance of getting an RC1-final published to nuget?  Looks like the code is all there.

**Comment by bradygaster** [comment]
I mistakingly added this bug to the SB repo here: https://github.com/domaindrivendev/Swashbuckle/issues/579

So closing either one should resolve both. 

@domaindrivendev - in the future what's the best place for vNext-related bugs? This repo or the SB repo?

**Comment by domaindrivendev** [comment]
This is essentially a dup of #37 which should be resolved as I've just released the rc1 compatible nuget.

@bradygaster - I know the two repos are a little confusing. As we approach a stable aspnet 5, I'll look to merge Ahoy back into the Swashbuckle repo - it's the same product afterall.

In the meantime, it would be ideal if you log vNext issues to the Ahoy repo

Cheers

**Comment by bradygaster** [comment]
OH sweetness and excellent! Any chance when the Nuget will be out too?

**Comment by domaindrivendev** [comment]
Nuget is out - Swashbuckle.6.0.0-rc1-final
