### ISSUE TITLE
Hello world example

### ISSUE THREAD

**Issue by damienbod** [domaindrivendev/Ahoy#46]
Hi 

I've created an example project showing some usages of your library. Maybe it could be of help for others.

http://damienbod.com/2015/12/13/asp-net-5-mvc-6-api-documentation-using-swagger/

Thanks for the code.

Greetings Damien

**Comment by domaindrivendev** [comment]
That's awesome - thx. I also have a couple of sample usages in this repo under tests\Websites.

You should take a look at Startup.cs in the "Basic" sample as it shows a relatively simple approach for wiring up Xml comments based on IApplicationEnvironment.

**Comment by jorgearteiro** [comment]
To make things easier for beginners we could have same or similar README.md front page as version 5. I am happy to write. let me know.
There are some break changes coming on next release??? looking Master branch, namespaces and startup.cs settings are different.
