### ISSUE TITLE
Move ConfigureSwaggerDocument and ConfigureSwaggerSchema from ConfigureServices to Configure in Setup

### ISSUE THREAD

**Issue by bluemmc** [domaindrivendev/Ahoy#48]
Currently ConfigureSwaggerDocument and ConfigureSwaggerSchema must be done in Setup.ConfigureServices of the client web project. At this stage the client knows nothing about the execution environment so it need to hardcode a full path the the documentation XML XmlComments file. Not nice!

It would be better if these can be done later in Setup.Configure where it is possible to use dependency injection to get hold of IApplicationEnvironment which allows for calculating where the XML XmlComments file is located relative to the ApplicationBasePath.

**Comment by domaindrivendev** [comment]
This doesn't really make sense to me as the configuration applies to the SwaggerProvider "service" and not the Swagger middleware. Besides, you can just create a constructor in your Startup class that accepts IApplicationEnvironment and then store it in an instance variable. Then it's accessible from the ConfigureServices method. See https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Startup.cs for an example that uses this approach.

**Comment by xperiandri** [comment]
You can get it even from Configuration

``` C#
var ContentRootPaths  = Configuration.GetChildren().Where(c => string.Compare(c.Value, env.ContentRootPath) == 0).ToList();
```

`Key = "ASPNETCORE_CONTENTROOT"`
`Key = "ASPNET_APPLICATIONBASE"`

**Comment by xperiandri** [comment]
This way `Configuration["ASPNETCORE_CONTENTROOT"]`
