### ISSUE TITLE
Produces attribute should win over SwaggerResponse attribute defaults

### ISSUE THREAD

**Issue by bluemmc** [domaindrivendev/Ahoy#49]
I prefer the Produces attribute which is standard ASP.NET (in vNext) to describe return types rather then swagger-specific SwaggerResponse attribute. Unfortunately, XML comments to specify return types is not supported so currently I have to specify a SwaggerResponse for return types. However if I specify SwaggerResponse then I have to specify a type parameter as well or it's default will overwrite the type in the Produces attribute with an empty-type. This means I have to specify the type multiple times as in the example below which I think is bad practice. I would like to remove the type specifier on the SwaggerResponse if I have a Produces attribute (p.s. and for XML comments to be supported as well - see issue #24)

````
[Produces(typeof(Employee))]
[SwaggerResponse(System.Net.HttpStatusCode.OK, Type=typeof(Employee))]
[SwaggerResponse(System.Net.HttpStatusCode.NotFound)]
```

**Comment by domaindrivendev** [comment]
Swashbuckle makes a massive effort to leverage standard constructs where possible. It's a fundamental part of the the philosophy to create "living documentation" according to implementation code as opposed to documentation-specific artifacts which inevitably go out of date. However, there are limits to what can be inferred from code and this is where SB provides extensibility points such as operation filters and Swagger annotations to fill in the gaps.

As I'm sure you're aware, Produces can only be used to describe successful responses, that is 200 or 204 in the case of void actions. I would always favor this over the the SwaggerResponse attribute. In fact, I typically only use the Swagger attributes to specify error (e.g. non-2xx) responses. I think you can do the same in your example above. For example:

    [Produces(typeof(Employee))]  // should document the 200 response
    [SwaggerResponse(HttpStatusCode.NotFound)]  // should document the 404 response

Also, just to keep things separated, let's leave the discussion around using Xml comments for response codes (which BTW requires "non-standard" Xml comment tags) to #24

**Comment by bluemmc** [comment]
Good point (on both accounts). I just checked and it works :-) 
I do not know if other non-error SwaggerReponses makes sense (SwaggerReponse with a description as well maybe? or special non-error codes) that means that this issue is still important, but for now your proposal works!
I am also happy that we agree on using standard constructs wherever possible. Swashbuckle could maybe consider submitting a new "standard-attribute" or "standard-comment" to the ASP.NET project (it is open source after all - maybe MS is open to the idea?).

**Comment by domaindrivendev** [comment]
Didn't even have to ask :) https://github.com/aspnet/Mvc/pull/4269/commits/3670144259e8d79c4c0c32c88741f437f1e5c065

Will get this baked in shortly

**Comment by Deilan** [comment]
If my opinion the following order should make sense:
1. If an action method is decorated with SwaggerResponseAttribute with an explicit Type value, then the Swagger UI should represent this.
2. Else if the method is decorated with vanilla Produces attribute, then the Swagger UI should represent this.
3. Else if the return value is NOT void and return type value does not implement IActionResult, then Swagger should represent the model of the declared return type.

**Comment by domaindrivendev** [comment]
As of beta902, SwaggerResponse attributes have been removed in favor of the built in ProducesResponseType attributes.

**Comment by mattfrear** [comment]
SwaggerResponse is supported in Swashbuckle.AspNetCore 1.0.0, so I guess this decision must have been reversed?

**Comment by lonix1** [comment]
@domaindrivendev Yes I'm also confused, the attribute is back? I have `Swashbuckle.AspNetCore.Annotations` from `Swashbuckle.AspNetCore.Annotations.dll`.

Which is the recommended way `SwaggerResponse` or `ProducesResponseType`?
