### ISSUE TITLE
Doesn't work with RC2

### ISSUE THREAD

**Issue by Inumedia** [domaindrivendev/Ahoy#54]
Swashbuckle throws an exception when calling 'UseSwaggerGen()'.

Exception:
>System.NullReferenceException: Object reference not set to an instance of an object.

Source Assembly:
>Swashbuckle.SwaggerGen

Stacktrace:
>at Microsoft.Extensions.DependencyInjection.SwaggerGenServiceCollectionExtensions.GetJsonSerializerSettings(IServiceProvider serviceProvider)
>at Microsoft.Extensions.DependencyInjection.SwaggerGenServiceCollectionExtensions.CreateSchemaRegistryFactory(IServiceProvider serviceProvider)
>at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.SingletonCallSite.Invoke(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.SwaggerGenServiceCollectionExtensions.CreateSwaggerProvider(IServiceProvider serviceProvider)
>at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.SingletonCallSite.Invoke(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
>at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>at Microsoft.AspNet.Builder.SwaggerGenBuilderExtensions.ThrowIfServiceNotRegistered(IServiceProvider applicationServices)
>at Microsoft.AspNet.Builder.SwaggerGenBuilderExtensions.UseSwaggerGen(IApplicationBuilder app, String routeTemplate)
>at %.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\..\Startup.cs:line 85

**Comment by Inumedia** [comment]
If there's anything I can do to help get this resolved asap let me know.

**Comment by domaindrivendev** [comment]
I'm a little confused by the title of this ticket - is AspNet 5 RC2 released?

**Comment by Inumedia** [comment]
Not yet, but will be soon. RC2 is currently available via beta channels.

**Comment by Inumedia** [comment]
This can largely be resolved by removing the dependency to 'Microsoft.Extensions.OptionsModel' in favor of 'Microsoft.Extensions.Options'. Changing that on my end seems to get everything working again.

I also had to add a call to AddOptions when configuring services.

"Swashbuckle.SwaggerGen\Application\SwaggerGenServiceCollectionExtensions.cs" is the only place I'm seeing it.

**Comment by endeffects** [comment]
I have the same problem. If i remove the dependency for OptionsModel i'm getting an error on services.AddSwaggerGen();

Managed Debugging Assistant 'BindingFailure' has detected a problem in ..\dnx-clr-win-x86.1.0.0-rc2-16357\bin\dnx.exe'.

Additional information: The assembly with display name 'Microsoft.Extensions.OptionsModel' failed to load in the 'Anonymous' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.OptionsModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

**Comment by Inumedia** [comment]
@endeffects Are you sure you're only loading the source version of Ahoy/SwaggerDocs vs the nuget package?

I don't recall having to do anything other than removing the reference in project.json to it and the using statement in the extensions.

**Comment by endeffects** [comment]
hmm, i'm working with the myget dev feeds (https://www.myget.org/gallery/swashbuckle). but the feed seems to be limited to rc1 only.

**Comment by Inumedia** [comment]
I have it working with compiling the source with the RC2 project.

**Comment by endeffects** [comment]
Ah ok, thanks. Than i have to wait, because i don't like to fork the project.

**Comment by Inumedia** [comment]
Also, as I found out today. In SwaggerGen's project.json there's a dependency for Newtonsoft for dnxcore50. This is no longer only for dnxcore50 as dnx451 doesn't include Newtonsoft.

**Comment by Inumedia** [comment]
@domaindrivendev Does it make sense for me to make a pull request once RC2 is released?

**Comment by kudoz83** [comment]
I'm attempting to experiment with this against RC2 and am not clear on the mods described by inumedia.  Are there any plans to publish an RC2 compatible package to nuget?  I hate to revert back to RC1 as RC2 is slated for general availability this month...

**Comment by FreakyJ** [comment]
I have swashbuckle running on RC2 locally. You just need to change the dependencies. :)

**Comment by Ciantic** [comment]
@FreakyJ basically search "Microsoft.AspNet" replace "Microsoft.AspNetCore"?

**Comment by Ciantic** [comment]
There is pull request /which is already outdated) but it contains more discussion and a fix: https://github.com/domaindrivendev/Ahoy/pull/72

**Comment by Ciantic** [comment]
I made a combined pull request, and updated it to function yesterday: https://github.com/domaindrivendev/Ahoy/pull/79

**Comment by domaindrivendev** [comment]
Dup of #84

**Comment by xperiandri** [comment]
Do you already have a build for RC2 on MyGet?

**Comment by domaindrivendev** [comment]
Striving for 5/28. See the beta2 milestone here https://github.com/domaindrivendev/Ahoy/milestones
