### ISSUE TITLE
JsonConverterAttribute not respected 

### ISSUE THREAD

**Issue by bluemmc** [domaindrivendev/Ahoy#56]
I am using a custom JsonConverter which is configured using an JsonConverterAttribute. It gets called and used in ASP.NET 5's controllers but Ahoy does not use it so the output shown in the model schema by Ahoy's GUI is wrong. 

Steps to reproduce:
A. Add a produce attribute to a controller method to inform Ahoy of the response type.
```
[Produces(typeof(IResource<Employment>))]
```

B. Add a JsonConverterAttribute to the above IResource<T> type
```
[JsonConverter(typeof(ResourceJsonConverter))]
```

The ResourceJsonConverter now gets called by ASP.NET 5 but not by Ahoy (bug)

**Comment by domaindrivendev** [comment]
Unfortunately you're out of luck here. Swashbuckle uses the "static" constructs in your code (classes attributes etc) to figure out what a Type would look like when serialized to JSON. However, when you use a JsonConverter, the serialization rules for that type get tied up in run-time logic and this makes it extremely difficult, if not impossible, to preemptively describe it.

**Comment by domaindrivendev** [comment]
Your best bet would be to create a custom Schema Filter (see readme). This gives you a hook to go in and modify the generated Schema for types in your API. It also gives you plenty of context (including the ApiDescription and the corresponding C# type) so you could check to see if the type has been decorated with your JsonConverter and if so modify it's Schema accordingly.
