### ISSUE TITLE
Can´t find xml comments from vnext/asp.net core projects in production enviroment

### ISSUE THREAD

**Issue by RichardSilveira** [domaindrivendev/Ahoy#67]
In Startup class from project "\test\WebSites\Basic" in "Ahoy" solution, i could observe that in the above code is only possible see the xml comments that sits above the controller's actions in development enviroment...

There is a way to do that in production enviroment?

```
if (_hostingEnv.IsDevelopment())
            {
                services.ConfigureSwaggerGen(c =>
                {
                    c.IncludeXmlComments(string.Format(@"{0}\artifacts\bin\Basic\{1}\{2}{3}\Basic.xml",
                        GetSolutionBasePath(),
                        _appEnv.Configuration,
                        _appEnv.RuntimeFramework.Identifier,
                        _appEnv.RuntimeFramework.Version.ToString().Replace(".", string.Empty)));
                });
            }
````

**Comment by domaindrivendev** [comment]
Yep, the sample code only works for dev environment. Take a look at #21, I think there's a solution for prod deploys in there. If you get it working, would be great to add to the example WebSite - I'm happy to accept a PR
