### ISSUE TITLE
How to configure root url in asp.net 5 (vnext)

### ISSUE THREAD

**Issue by RichardSilveira** [domaindrivendev/Ahoy#68]
In previous version of Swashbuckle, for asp.net web api 2 there is the "RootUrl" extension method that adds the capabilite to customize the root url.
````
httpConfiguration
    .EnableSwagger(c =>
        {
            c.RootUrl(req => GetRootUrlFromAppConfig());
````
So, when testing my application in localhost (http://localhost:63563/swagger/ui/index.html), everything works fine, but in staging (or production) my url becomes http://my-app.com/ **api** /swagger/ui/index.htm.

I've done a lot of research, but i can´t found anything usefull from my case...
Is it really an issue of this version? Can anyone help me on this?

**Comment by domaindrivendev** [comment]
Possible in beta902 via special filter that has request context. See below for an example:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Startup.cs#L74

**Comment by domaindrivendev** [comment]
Should be resolved in beta902
