### ISSUE TITLE
Add support for dnxcore50

### ISSUE THREAD

**Issue by rynowak** [domaindrivendev/Ahoy#7]
We should add support for building CoreCLR (dnxcore50).

I was able to prototype it pretty easily by adding this to project.json:
```
    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Xml.XPath": "4.0.0-beta-*"
            }
        }
    }
```

The only extra dependency needed was xpath. Consider doing the same for the tests.

Doing a `dnu restore` `dnu build` will build for both flavors.

**Comment by domaindrivendev** [comment]
See Swashbuckle 6.0.0-beta2
