### ISSUE TITLE
SwaggerResponse with Type Not Showing in Response Messages

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Ahoy#77]
I have the following controller action with a `[SwaggerResponse]` attribute on it but the 200 OK response is not showing in the 'Response Messages' section of the Swagger UI until I remove the `Type` from it.

```
[HttpGet("{academyId:int:min(1)}", Name = "GetAcademy")]
[Produces(typeof(Academy))]
[SwaggerResponse(
    HttpStatusCode.OK, 
    "Returns the Academy with the specified Academy ID.", 
    typeof(Academy))]
[SwaggerResponse(
    HttpStatusCode.NotFound, 
    "An Academy with the specified Academy ID was not found.")]
public async Task<IActionResult> Get(int academyId) { }
```

**Comment by JefStat** [comment]
It will not show in the response messages while you have the `[Produces]` `Type` but if you add back the `Type` to `SwaggerResponse` it will show right below the path with the `Response Class 200` heading ie:

![image](https://cloud.githubusercontent.com/assets/583018/16207166/b831d8de-36f9-11e6-9fbb-c5df94dc1ef4.png)

**Comment by domaindrivendev** [comment]
The SwaggerResponseAttribute has been removed in favor of AspNet Core's built-in "ProducesResponseTypeAttribute. Is this still causing an issue with the latest release v6.0.0-beta902?

**Comment by RehanSaeed** [comment]
Seems fine.
