### ISSUE TITLE
Forcing UI to Require HTTPS

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Ahoy#82]
I have added the `RequireHttpsAttribute` filter but the Ahoy UI does not redirect to the HTTPS version of the site. What is the best way to achieve this?

**Comment by domaindrivendev** [comment]
There's nothing built-in for this but you could implement very easily with a simple middleware delegate. Something along the lines of the inline middleware (in _Startup.cs_) shown below should do the trick:

```csharp
app.UseSwagger();

app.Use(async (context, next) =>
{
    var request = context.Request;
    if (request.Path == "/swagger" && !request.IsHttps)
        context.Response.Redirect("https://" + request.Host + request.Path);
    else
        await next();
});

app.UseSwaggerUi();
```

**Comment by RehanSaeed** [comment]
There is a new redirect middleware coming out as part of ASP.NET Core 1.1.0. Will wait and see if that can be used.
