### ISSUE TITLE
Publish nuget package

### ISSUE THREAD

**Issue by operezfuentes** [domaindrivendev/Ahoy#9]
Hi,

I'm very interested to begin to use it with asp.net 5 beta5.

Pls, can you publish as nuget package i.e. https://www.nuget.org/packages/Swashbuckle/6.0.0-beta2

Thanks!

**Comment by domaindrivendev** [comment]
It's top of my priority list! I just need to carve out hours to do it - hopefully this weekend

**Comment by domaindrivendev** [comment]
Beta2 released!

**Comment by rynowak** [comment]
:fireworks:
