### ISSUE TITLE
Mapping WebApiCompatShim routes

### ISSUE THREAD

**Issue by cecilphillip** [domaindrivendev/Ahoy#94]
Is there anything special I need to do to get SwashBuckle to recognize ApiControllers from WebApiCompatShim without attribute routing? My routes are currently setup like this

**Startup.cs**
``` csharp
 routes.MapWebApiRoute(
                    name: "apiRoute",
                    template: "api/{controller}/{action}");
```

**Controller**
``` csharp
 public class RegistationController : ApiController
    {
        [HttpGet]
        public HttpResponseMessage List()
        {
            var results = .... ;
            if (results.Any()) return Request.CreateResponse(HttpStatusCode.OK, results);

            return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Nobody Registered" );
        }
    }
```

MVC 6/Core matches the route but it doesn't get picked up by swagger

**Comment by ruben0909** [comment]
+1

**Comment by rynowak** [comment]
There's no support for ApiExplorer/Swashbuckle using conventional routing.  We strongly recommend using attribute routing for building any API. If you want to, as @ruben0909 suggested you can use a route like `[Route("api/[controller]/[action]")]` to do something similar and keep it DRY.

**Comment by cecilphillip** [comment]
Ok. Thanks guys
